#pragma once

#include <random>

namespace dnd_character {

// Return a random ability score between 3 and 18.
// The score is generated by rolling four 6-sided dice and summing the
// highest three results.
int ability();

// Calculate the ability modifier for a given score.
// This is ⌊(score − 10) / 2⌋.
int modifier(int score);

// A D&D character with six ability scores and hit points.
struct Character {
    int strength;
    int dexterity;
    int constitution;
    int intelligence;
    int wisdom;
    int charisma;
    int hitpoints;

    Character();
};

}  // namespace dnd_character
